### ISSUE TITLE
Is it critical that this depends on qt-main?

### ISSUE THREAD

**Issue by hmaarrfk** [conda-forge/nsight-compute-feedstock#15]
It depends on qt-main which is somewhat outdated in 2024. It would help users experiment with qt6 more freely.

It would be good to have:

-  noqt
- qt5
- qt6

 maybe similar to https://github.com/conda-forge/opencv-feedstock/pull/396

**Comment by jakirkham** [comment]
It's worth noting that this is binary repackaging

That said, looking at the logs, see lines like this [on CI]( https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=890155&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=2562 ):

```
   INFO (nsight-compute,nsight-compute-2024.1.0/host/linux-desktop-glibc_2_11_3-x64/libQt6Test.so.6): Needed DSO nsight-compute-2024.1.0/host/linux-desktop-glibc_2_11_3-x64/libQt6Core.so.6 found in the whitelist
   ...
   INFO (nsight-compute,nsight-compute-2024.1.0/host/linux-desktop-glibc_2_11_3-x64/Plugins/imageformats/libqgif.so): Needed DSO $RPATH/libQt6Core.so.6 found in the whitelist
   ...
   INFO (nsight-compute,nsight-compute-2024.1.0/host/linux-desktop-glibc_2_11_3-x64/Plugins/imageformats/libqtga.so): Needed DSO $RPATH/libQt6Core.so.6 found in the whitelist
```

So think it should be Qt6 instead of Qt5

**Comment by hmaarrfk** [comment]
It also seems to pack its own version of qt6....

files like this seem to exist
```
nsight-compute,nsight-compute-2024.1.0/host/linux-desktop-glibc_2_11_3-x64/libQt6DBus.so.6
```

**Comment by jakirkham** [comment]
Yeah looking at the history `qt-main` was added in PR: https://github.com/conda-forge/nsight-compute-feedstock/pull/7

Appears this was added to fix a test with `ncu-ui`: https://github.com/conda-forge/nsight-compute-feedstock/pull/7/commits/de9ed4482f82764c9dd2b3f344a6e6e134ceb799

**Comment by hmaarrfk** [comment]
@conda-forge-admin please rerender

**Comment by jakirkham** [comment]
Given PR ( https://github.com/conda-forge/nsight-compute-feedstock/pull/16 ) has since been merged, this appears to be resolved. Going to close this out. Please let us know if anything else comes up
